### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by dmehus**
Feel free to add to this later

### CODE REVIEW

**Comment by Universal-Omega** [comment]
The way you explain this explains it as if they will always set the config that way, that makes it to Miraheze specific, which I want this to be usable outside MH also, like our other extensions. The explanation only explains the way we plan to use the configs.

**Comment by dmehus** [comment]
> The way you explain this explains it as if they will always set the config that way, that makes it to Miraheze specific, which I want this to be usable outside MH also, like our other extensions. The explanation only explains the way we plan to use the configs.

I tried not to make it Miraheze-specific. What should I change?

**Comment by Universal-Omega** [comment]
> > The way you explain this explains it as if they will always set the config that way, that makes it to Miraheze specific, which I want this to be usable outside MH also, like our other extensions. The explanation only explains the way we plan to use the configs.
> 
> I tried not to make it Miraheze-specific. What should I change?

> Depending on their role, they will select one of two prefix options to append to the randomly generated hash.

**Comment by dmehus** [comment]
> Depending on their role, they will select one of two prefix options to append to the randomly generated hash.

Would this work better:

"The special page allows for various prefixes to be appended to the randomly generated hash."?

**Comment by dmehus** [comment]
> > > Depending on their role, they will select one of two prefix options to append to the randomly generated hash.
> > 
> > 
> > Would this work better:
> > "The special page allows for various prefixes to be appended to the randomly generated hash."?
> 
> If you just remove that whole line, I can document the 2 configuration options in a later PR, or I could append this change to my PR and document it there if you want?

Sure! I can do that.

**Comment by Universal-Omega** [comment]
> > > > Depending on their role, they will select one of two prefix options to append to the randomly generated hash.
> > > 
> > > 
> > > Would this work better:
> > > "The special page allows for various prefixes to be appended to the randomly generated hash."?
> > 
> > 
> > If you just remove that whole line, I can document the 2 configuration options in a later PR, or I could append this change to my PR and document it there if you want?
> 
> Sure! I can do that.

Thanks!

**Review by Universal-Omega — APPROVED** [review]

**Comment by dmehus** [comment]
> > > > > Depending on their role, they will select one of two prefix options to append to the randomly generated hash.
> > > > 
> > > > 
> > > > Would this work better:
> > > > "The special page allows for various prefixes to be appended to the randomly generated hash."?
> > > 
> > > 
> > > If you just remove that whole line, I can document the 2 configuration options in a later PR, or I could append this change to my PR and document it there if you want?
> > 
> > 
> > Sure! I can do that.
> 
> Thanks!

No problem. Thanks so much for building phase one so quickly! :)

**Pull request merged**
